export interface Project {
  id: string
  name: string
  date: string        // MM/DD/YYYY bid date
  location: string    // "City, State"
  docs: string
  datePosted: string  // YYYY-MM-DD
  stage: string       // "Bidding" | "Pre-Bid" | "Awarded"
  value: string
  state: string       // 2-letter lowercase
  county: string      // county name without "County"
  trades: string[]
  buildingUse: string
  constructionType: string
  projectType: string
  keywords: string[]
  laborStatus: string
  distance?: string
  zip: string
}

export const ALL_PROJECTS: Project[] = [
  // ── 20 FULL-MATCH CA SECURITY PROJECTS ──────────────────────────────────────
  {
    id: "p1", name: "Los Angeles USD Surveillance System Upgrade",
    date: "03/22/2026", location: "Los Angeles, California", zip: "90012",
    docs: "Matches Found", datePosted: "2026-03-18", stage: "Bidding", value: "$1.2M",
    state: "ca", county: "Los Angeles", trades: ["electrical-low-voltage", "specialties"],
    buildingUse: "educational-school-university", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "prevailing-wage",
    keywords: ["CCTV", "surveillance", "security camera", "access control"],
  },
  {
    id: "p2", name: "Kaiser Permanente San Jose Security Integration",
    date: "03/22/2026", location: "San Jose, California", zip: "95113",
    docs: "Matches Found", datePosted: "2026-03-17", stage: "Bidding", value: "$870K",
    state: "ca", county: "Santa Clara", trades: ["electrical-low-voltage", "special-construction"],
    buildingUse: "clinic-hospital-medical", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "non-union",
    keywords: ["access control", "security camera", "card reader", "security system"],
  },
  {
    id: "p3", name: "Sacramento City Hall Access Control Modernization",
    date: "03/23/2026", location: "Sacramento, California", zip: "95814",
    docs: "Matches Found", datePosted: "2026-03-16", stage: "Bidding", value: "$640K",
    state: "ca", county: "Sacramento", trades: ["electrical-low-voltage", "specialties"],
    buildingUse: "municipal", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "prevailing-wage",
    keywords: ["access control", "card reader", "security system", "intercom"],
  },
  {
    id: "p4", name: "BART Concord Station Security Camera System",
    date: "03/24/2026", location: "Concord, California", zip: "94519",
    docs: "Matches Found", datePosted: "2026-03-20", stage: "Bidding", value: "$980K",
    state: "ca", county: "Contra Costa", trades: ["electrical-low-voltage"],
    buildingUse: "transportation-terminal", constructionType: "civil",
    projectType: "new-construction-no-site-work", laborStatus: "prevailing-wage",
    keywords: ["CCTV", "surveillance", "security camera"],
  },
  {
    id: "p5", name: "San Diego USD Intrusion Detection Upgrade",
    date: "02/05/2026", location: "San Diego, California", zip: "92101",
    docs: "Matches Found", datePosted: "2026-03-19", stage: "Bidding", value: "$510K",
    state: "ca", county: "San Diego", trades: ["specialties", "electrical-low-voltage"],
    buildingUse: "educational-school-university", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "prevailing-wage",
    keywords: ["intrusion detection", "alarm", "security system"],
  },
  {
    id: "p6", name: "UC Berkeley Integrated Security System Renovation",
    date: "02/08/2026", location: "Berkeley, California", zip: "94710",
    docs: "Matches Found", datePosted: "2026-03-21", stage: "Bidding", value: "$2.1M",
    state: "ca", county: "Alameda", trades: ["electrical-low-voltage", "special-construction"],
    buildingUse: "educational-school-university", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "prevailing-wage",
    keywords: ["CCTV", "access control", "security camera", "surveillance"],
  },
  {
    id: "p7", name: "LA Metro Red Line Video Surveillance Expansion",
    date: "03/24/2026", location: "Los Angeles, California", zip: "90012",
    docs: "Matches Found", datePosted: "2026-03-15", stage: "Bidding", value: "$3.4M",
    state: "ca", county: "Los Angeles", trades: ["electrical-low-voltage"],
    buildingUse: "transportation-terminal", constructionType: "civil",
    projectType: "renovation-remodel-repair", laborStatus: "prevailing-wage",
    keywords: ["CCTV", "surveillance", "security camera"],
  },
  {
    id: "p8", name: "Stanford Health Care Security Access System",
    date: "02/12/2026", location: "Palo Alto, California", zip: "94301",
    docs: "Matches Found", datePosted: "2026-03-14", stage: "Pre-Bid", value: "$760K",
    state: "ca", county: "Santa Clara", trades: ["electrical-low-voltage", "specialties"],
    buildingUse: "clinic-hospital-medical", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "non-union",
    keywords: ["access control", "card reader", "intercom", "security camera"],
  },
  {
    id: "p9", name: "Fresno County Detention Facility Access Control",
    date: "02/15/2026", location: "Fresno, California", zip: "93721",
    docs: "Matches Found", datePosted: "2026-03-12", stage: "Bidding", value: "$1.9M",
    state: "ca", county: "Fresno", trades: ["special-construction", "electrical-low-voltage"],
    buildingUse: "jail-prison", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "prevailing-wage",
    keywords: ["access control", "card reader", "security system"],
  },
  {
    id: "p10", name: "San Francisco City Hall Security Modernization",
    date: "03/25/2026", location: "San Francisco, California", zip: "94102",
    docs: "Matches Found", datePosted: "2026-03-18", stage: "Bidding", value: "$1.1M",
    state: "ca", county: "San Francisco", trades: ["electrical-low-voltage", "specialties"],
    buildingUse: "municipal", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "prevailing-wage",
    keywords: ["access control", "security camera", "intercom", "surveillance"],
  },
  {
    id: "p11", name: "Orange County Sheriff Campus CCTV Upgrade",
    date: "03/25/2026", location: "Santa Ana, California", zip: "92701",
    docs: "Matches Found", datePosted: "2026-03-10", stage: "Bidding", value: "$2.3M",
    state: "ca", county: "Orange", trades: ["electrical-low-voltage", "special-construction"],
    buildingUse: "fire-police-station", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "prevailing-wage",
    keywords: ["CCTV", "surveillance", "intrusion detection"],
  },
  {
    id: "p12", name: "San Jose International Airport Security Integration",
    date: "03/26/2026", location: "San Jose, California", zip: "95113",
    docs: "Matches Found", datePosted: "2026-03-08", stage: "Bidding", value: "$4.7M",
    state: "ca", county: "Santa Clara", trades: ["electrical-low-voltage", "specialties"],
    buildingUse: "transportation-terminal", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "prevailing-wage",
    keywords: ["security camera", "access control", "surveillance"],
  },
  {
    id: "p13", name: "Long Beach USD School Alarm System Replacement",
    date: "02/18/2026", location: "Long Beach, California", zip: "90802",
    docs: "Matches Found", datePosted: "2026-03-20", stage: "Bidding", value: "$430K",
    state: "ca", county: "Los Angeles", trades: ["specialties"],
    buildingUse: "educational-school-university", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "prevailing-wage",
    keywords: ["alarm", "intrusion detection", "security system"],
  },
  {
    id: "p14", name: "Dignity Health Stockton Campus Security System",
    date: "02/22/2026", location: "Stockton, California", zip: "95202",
    docs: "Matches Found", datePosted: "2026-03-05", stage: "Bidding", value: "$690K",
    state: "ca", county: "San Joaquin", trades: ["electrical-low-voltage"],
    buildingUse: "clinic-hospital-medical", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "non-union",
    keywords: ["access control", "security camera", "card reader"],
  },
  {
    id: "p15", name: "Caltrans District 4 Freeway CCTV Expansion",
    date: "02/26/2026", location: "Oakland, California", zip: "94612",
    docs: "Matches Found", datePosted: "2026-03-16", stage: "Bidding", value: "$5.2M",
    state: "ca", county: "Alameda", trades: ["electrical-low-voltage"],
    buildingUse: "road-highway", constructionType: "civil",
    projectType: "new-construction-no-site-work", laborStatus: "prevailing-wage",
    keywords: ["CCTV", "surveillance", "security camera"],
  },
  {
    id: "p16", name: "San Diego Convention Center Security Overhaul",
    date: "03/26/2026", location: "San Diego, California", zip: "92101",
    docs: "Matches Found", datePosted: "2026-03-11", stage: "Pre-Bid", value: "$1.6M",
    state: "ca", county: "San Diego", trades: ["electrical-low-voltage", "special-construction"],
    buildingUse: "conference-convention-center", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "non-union",
    keywords: ["access control", "security camera", "intercom"],
  },
  {
    id: "p17", name: "Riverside USD School District Security Upgrade",
    date: "03/27/2026", location: "Riverside, California", zip: "92501",
    docs: "Matches Found", datePosted: "2026-03-09", stage: "Bidding", value: "$780K",
    state: "ca", county: "Riverside", trades: ["specialties", "electrical-low-voltage"],
    buildingUse: "educational-school-university", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "prevailing-wage",
    keywords: ["access control", "alarm", "security system"],
  },
  {
    id: "p18", name: "LA County Superior Court Security Integration",
    date: "03/27/2026", location: "Los Angeles, California", zip: "90012",
    docs: "Matches Found", datePosted: "2026-03-17", stage: "Bidding", value: "$3.0M",
    state: "ca", county: "Los Angeles", trades: ["electrical-low-voltage", "special-construction"],
    buildingUse: "municipal", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "prevailing-wage",
    keywords: ["access control", "CCTV", "security camera"],
  },
  {
    id: "p19", name: "Caltrain Peninsula Corridor Security Cameras",
    date: "03/01/2026", location: "San Mateo, California", zip: "94401",
    docs: "Matches Found", datePosted: "2026-03-13", stage: "Pre-Bid", value: "$2.8M",
    state: "ca", county: "San Mateo", trades: ["electrical-low-voltage"],
    buildingUse: "transportation-terminal", constructionType: "civil",
    projectType: "new-construction-no-site-work", laborStatus: "prevailing-wage",
    keywords: ["surveillance", "CCTV", "security camera"],
  },
  {
    id: "p20", name: "UCSD Medical Center Integrated Security System",
    date: "03/28/2026", location: "San Diego, California", zip: "92101",
    docs: "Matches Found", datePosted: "2026-03-19", stage: "Bidding", value: "$1.4M",
    state: "ca", county: "San Diego", trades: ["electrical-low-voltage", "specialties"],
    buildingUse: "clinic-hospital-medical", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "non-union",
    keywords: ["access control", "card reader", "security camera", "surveillance"],
  },

  // ── CA NON-SECURITY PROJECTS ────────────────────────────────────────────────
  {
    id: "p21", name: "Google Santa Clara Data Center Phase 2",
    date: "03/03/2026", location: "Santa Clara, California", zip: "95050",
    docs: "Available", datePosted: "2026-03-10", stage: "Pre-Bid", value: "$42M",
    state: "ca", county: "Santa Clara", trades: ["electrical-low-voltage", "hvac", "plumbing"],
    buildingUse: "office", constructionType: "commercial",
    projectType: "new-construction-with-site-work", laborStatus: "non-union",
    keywords: ["data center", "MEP", "electrical"],
  },
  {
    id: "p22", name: "SF Bay Bridge East Span Seismic Retrofit",
    date: "03/05/2026", location: "San Francisco, California", zip: "94102",
    docs: "Available", datePosted: "2026-03-01", stage: "Bidding", value: "$28M",
    state: "ca", county: "San Francisco", trades: ["metal-steel-construction", "concrete-construction"],
    buildingUse: "bridges-tunnels", constructionType: "civil",
    projectType: "renovation-remodel-repair", laborStatus: "prevailing-wage",
    keywords: ["bridge", "seismic", "structural steel"],
  },
  {
    id: "p23", name: "Pasadena City College Science Building Addition",
    date: "03/07/2026", location: "Pasadena, California", zip: "91101",
    docs: "Available", datePosted: "2026-02-28", stage: "Bidding", value: "$18M",
    state: "ca", county: "Los Angeles", trades: ["concrete-construction", "masonry-construction", "hvac"],
    buildingUse: "educational-school-university", constructionType: "commercial",
    projectType: "addition", laborStatus: "prevailing-wage",
    keywords: ["classroom", "laboratory", "HVAC"],
  },
  {
    id: "p24", name: "LAX Terminal 9 Interior Renovation",
    date: "03/28/2026", location: "Los Angeles, California", zip: "90012",
    docs: "Available", datePosted: "2026-02-20", stage: "Pre-Bid", value: "$11M",
    state: "ca", county: "Los Angeles", trades: ["interior-walls-ceilings-insulation", "flooring", "painting-wallcovering"],
    buildingUse: "transportation-terminal", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "prevailing-wage",
    keywords: ["terminal", "flooring", "interior renovation"],
  },
  {
    id: "p25", name: "UCSF Mission Bay Research Lab Expansion",
    date: "03/29/2026", location: "San Francisco, California", zip: "94102",
    docs: "Available", datePosted: "2026-02-15", stage: "Pre-Bid", value: "$34M",
    state: "ca", county: "San Francisco", trades: ["concrete-construction", "hvac", "plumbing"],
    buildingUse: "laboratory", constructionType: "commercial",
    projectType: "addition", laborStatus: "non-union",
    keywords: ["lab", "clean room", "mechanical"],
  },
  {
    id: "p26", name: "Sacramento Kaiser Medical Office Building",
    date: "03/29/2026", location: "Sacramento, California", zip: "95814",
    docs: "Available", datePosted: "2026-02-10", stage: "Pre-Bid", value: "$8.5M",
    state: "ca", county: "Sacramento", trades: ["hvac", "plumbing", "electrical-low-voltage"],
    buildingUse: "medical", constructionType: "commercial",
    projectType: "new-construction-with-site-work", laborStatus: "non-union",
    keywords: ["medical office", "MEP", "HVAC"],
  },
  {
    id: "p27", name: "LA Rams SoFi Stadium Parking Structure",
    date: "03/30/2026", location: "Inglewood, California", zip: "90301",
    docs: "Available", datePosted: "2026-03-01", stage: "Bidding", value: "$22M",
    state: "ca", county: "Los Angeles", trades: ["concrete-construction", "demolition-site-construction"],
    buildingUse: "parking-garage", constructionType: "commercial",
    projectType: "new-construction-with-site-work", laborStatus: "union",
    keywords: ["parking structure", "concrete", "cast-in-place"],
  },
  {
    id: "p28", name: "San Jose City Hall Plaza Renovation",
    date: "03/30/2026", location: "San Jose, California", zip: "95113",
    docs: "Available", datePosted: "2026-03-05", stage: "Pre-Bid", value: "$4.2M",
    state: "ca", county: "Santa Clara", trades: ["exterior-improvements-landscaping", "concrete-construction"],
    buildingUse: "municipal", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "prevailing-wage",
    keywords: ["plaza", "landscaping", "hardscape"],
  },
  {
    id: "p29", name: "Sunnyvale Mixed-Use Transit Village",
    date: "03/31/2026", location: "Sunnyvale, California", zip: "94086",
    docs: "Available", datePosted: "2026-03-08", stage: "Pre-Bid", value: "$95M",
    state: "ca", county: "Santa Clara", trades: ["concrete-construction", "metal-steel-construction", "roofing-thermal-moisture"],
    buildingUse: "mixed-use", constructionType: "multi-family-residential",
    projectType: "new-construction-with-site-work", laborStatus: "union",
    keywords: ["mixed-use", "transit-oriented", "multi-family"],
  },
  {
    id: "p30", name: "Irvine Spectrum Business Park Phase 3",
    date: "03/31/2026", location: "Irvine, California", zip: "92612",
    docs: "Available", datePosted: "2026-03-12", stage: "Pre-Bid", value: "$17M",
    state: "ca", county: "Orange", trades: ["metal-steel-construction", "roofing-thermal-moisture", "exterior-siding-masonry"],
    buildingUse: "office", constructionType: "commercial",
    projectType: "new-construction-with-site-work", laborStatus: "non-union",
    keywords: ["office park", "tilt-up", "roofing"],
  },

  // ── WASHINGTON STATE PROJECTS ────────────────────────────────────────────────
  {
    id: "p31", name: "Microsoft Campus Building 44 Expansion",
    date: "04/01/2026", location: "Redmond, Washington", zip: "98052",
    docs: "Available", datePosted: "2026-03-14", stage: "Pre-Bid", value: "$4.2M",
    state: "wa", county: "King", trades: ["electrical-low-voltage", "hvac", "interior-walls-ceilings-insulation"],
    buildingUse: "office", constructionType: "commercial",
    projectType: "addition", laborStatus: "non-union",
    keywords: ["office expansion", "MEP", "tenant improvement"],
  },
  {
    id: "p32", name: "Seattle Children's Hospital Wing C Renovation",
    date: "04/01/2026", location: "Seattle, Washington", zip: "98101",
    docs: "Available", datePosted: "2026-03-16", stage: "Bidding", value: "$12M",
    state: "wa", county: "King", trades: ["hvac", "plumbing", "electrical-low-voltage"],
    buildingUse: "clinic-hospital-medical", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "union",
    keywords: ["hospital", "MEP", "renovation"],
  },
  {
    id: "p33", name: "Tacoma Public Library Renovation",
    date: "03/08/2026", location: "Tacoma, Washington", zip: "98401",
    docs: "Matches Found", datePosted: "2026-03-17", stage: "Bidding", value: "$1.8M",
    state: "wa", county: "Pierce", trades: ["interior-walls-ceilings-insulation", "flooring", "electrical-low-voltage"],
    buildingUse: "library", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "prevailing-wage",
    keywords: ["library", "renovation", "ADA"],
  },
  {
    id: "p34", name: "Auburn School District HVAC Upgrade",
    date: "04/02/2026", location: "Auburn, Washington", zip: "98001",
    docs: "Available", datePosted: "2026-03-10", stage: "Pre-Bid", value: "$890K",
    state: "wa", county: "King", trades: ["hvac"],
    buildingUse: "educational-school-university", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "prevailing-wage",
    keywords: ["HVAC", "school", "mechanical"],
  },
  {
    id: "p35", name: "Bellevue Tech Campus Phase 2",
    date: "04/02/2026", location: "Bellevue, Washington", zip: "98004",
    docs: "Matches Found", datePosted: "2026-03-08", stage: "Bidding", value: "$28M",
    state: "wa", county: "King", trades: ["metal-steel-construction", "concrete-construction", "exterior-siding-masonry"],
    buildingUse: "office", constructionType: "commercial",
    projectType: "new-construction-with-site-work", laborStatus: "union",
    keywords: ["tech campus", "office", "structural steel"],
  },
  {
    id: "p36", name: "Renton Community Center Addition",
    date: "04/03/2026", location: "Renton, Washington", zip: "98057",
    docs: "Available", datePosted: "2026-03-05", stage: "Bidding", value: "$3.4M",
    state: "wa", county: "King", trades: ["concrete-construction", "roofing-thermal-moisture", "hvac"],
    buildingUse: "community-center", constructionType: "commercial",
    projectType: "addition", laborStatus: "prevailing-wage",
    keywords: ["community center", "addition", "recreation"],
  },
  {
    id: "p37", name: "Federal Way Fire Station No. 63",
    date: "04/03/2026", location: "Federal Way, Washington", zip: "98003",
    docs: "Available", datePosted: "2026-02-28", stage: "Pre-Bid", value: "$5.1M",
    state: "wa", county: "King", trades: ["concrete-construction", "metal-steel-construction", "hvac"],
    buildingUse: "fire-police-station", constructionType: "commercial",
    projectType: "new-construction-with-site-work", laborStatus: "prevailing-wage",
    keywords: ["fire station", "new construction"],
  },
  {
    id: "p38", name: "Kirkland Waterfront Mixed-Use Development",
    date: "04/04/2026", location: "Kirkland, Washington", zip: "98033",
    docs: "Matches Found", datePosted: "2026-02-20", stage: "Bidding", value: "$67M",
    state: "wa", county: "King", trades: ["concrete-construction", "metal-steel-construction", "plumbing"],
    buildingUse: "mixed-use", constructionType: "multi-family-residential",
    projectType: "new-construction-with-site-work", laborStatus: "union",
    keywords: ["mixed-use", "waterfront", "residential"],
  },
  {
    id: "p39", name: "Everett Naval Station Barracks Renovation",
    date: "04/04/2026", location: "Everett, Washington", zip: "98201",
    docs: "Available", datePosted: "2026-02-15", stage: "Awarded", value: "$18M",
    state: "wa", county: "Snohomish", trades: ["roofing-thermal-moisture", "interior-walls-ceilings-insulation", "hvac"],
    buildingUse: "military", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "prevailing-wage",
    keywords: ["military", "barracks", "renovation"],
  },
  {
    id: "p40", name: "Bothell Medical Office Building",
    date: "04/05/2026", location: "Bothell, Washington", zip: "98021",
    docs: "Matches Found", datePosted: "2026-03-12", stage: "Pre-Bid", value: "$7.6M",
    state: "wa", county: "Snohomish", trades: ["hvac", "plumbing", "electrical-low-voltage"],
    buildingUse: "medical", constructionType: "commercial",
    projectType: "new-construction-with-site-work", laborStatus: "non-union",
    keywords: ["medical office", "MOB", "MEP"],
  },
  {
    id: "p41", name: "Shoreline Light Rail Station Parking Garage",
    date: "04/05/2026", location: "Shoreline, Washington", zip: "98133",
    docs: "Available", datePosted: "2026-03-01", stage: "Bidding", value: "$14M",
    state: "wa", county: "King", trades: ["concrete-construction", "electrical-low-voltage"],
    buildingUse: "parking-garage", constructionType: "commercial",
    projectType: "new-construction-with-site-work", laborStatus: "prevailing-wage",
    keywords: ["parking garage", "transit", "concrete"],
  },
  {
    id: "p42", name: "Redmond Elementary School Rebuild",
    date: "04/06/2026", location: "Redmond, Washington", zip: "98052",
    docs: "Available", datePosted: "2026-03-16", stage: "Pre-Bid", value: "$22M",
    state: "wa", county: "King", trades: ["concrete-construction", "roofing-thermal-moisture", "hvac"],
    buildingUse: "educational-school-university", constructionType: "commercial",
    projectType: "new-construction-with-site-work", laborStatus: "prevailing-wage",
    keywords: ["school", "new construction", "K-12"],
  },
  {
    id: "p43", name: "Issaquah Senior Living Facility",
    date: "03/10/2026", location: "Issaquah, Washington", zip: "98027",
    docs: "Matches Found", datePosted: "2026-03-13", stage: "Bidding", value: "$31M",
    state: "wa", county: "King", trades: ["concrete-construction", "metal-steel-construction", "hvac", "plumbing"],
    buildingUse: "assisted-living", constructionType: "commercial",
    projectType: "new-construction-with-site-work", laborStatus: "non-union",
    keywords: ["senior living", "assisted living", "new construction"],
  },
  {
    id: "p44", name: "Kent Warehouse Distribution Center",
    date: "04/06/2026", location: "Kent, Washington", zip: "98032",
    docs: "Available", datePosted: "2026-02-10", stage: "Bidding", value: "$9.8M",
    state: "wa", county: "King", trades: ["metal-steel-construction", "concrete-construction", "roofing-thermal-moisture"],
    buildingUse: "warehouse-distribution", constructionType: "industrial",
    projectType: "new-construction-with-site-work", laborStatus: "non-union",
    keywords: ["warehouse", "tilt-up", "distribution"],
  },
  {
    id: "p45", name: "Top Pot Doughnuts Foundry Cafe Tenant Improvement",
    date: "04/07/2026", location: "Kent, Washington", zip: "98032",
    docs: "Matches Found", datePosted: "2026-03-15", stage: "Bidding", value: "$240K",
    state: "wa", county: "King", trades: ["interior-walls-ceilings-insulation", "flooring", "plumbing"],
    buildingUse: "restaurant", constructionType: "commercial",
    projectType: "tenant-build-out", laborStatus: "non-union",
    keywords: ["restaurant", "tenant improvement", "TI"],
  },

  // ── TEXAS PROJECTS ───────────────────────────────────────────────────────────
  {
    id: "p46", name: "Houston ISD Elementary School Security Upgrade",
    date: "04/07/2026", location: "Houston, Texas", zip: "77002",
    docs: "Matches Found", datePosted: "2026-03-18", stage: "Bidding", value: "$620K",
    state: "tx", county: "Harris", trades: ["electrical-low-voltage", "specialties"],
    buildingUse: "educational-school-university", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "non-union",
    keywords: ["security camera", "access control", "alarm"],
  },
  {
    id: "p47", name: "Dallas Fort Worth Airport Terminal D Renovation",
    date: "03/11/2026", location: "Irving, Texas", zip: "75063",
    docs: "Available", datePosted: "2026-03-12", stage: "Pre-Bid", value: "$38M",
    state: "tx", county: "Dallas", trades: ["interior-walls-ceilings-insulation", "flooring", "hvac", "electrical-low-voltage"],
    buildingUse: "transportation-terminal", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "non-union",
    keywords: ["airport", "terminal", "renovation"],
  },
  {
    id: "p48", name: "Austin Tech Office Campus Phase 1",
    date: "03/12/2026", location: "Austin, Texas", zip: "78701",
    docs: "Available", datePosted: "2026-03-05", stage: "Pre-Bid", value: "$55M",
    state: "tx", county: "Travis", trades: ["concrete-construction", "metal-steel-construction", "hvac"],
    buildingUse: "office", constructionType: "commercial",
    projectType: "new-construction-with-site-work", laborStatus: "non-union",
    keywords: ["office campus", "tech", "new construction"],
  },
  {
    id: "p49", name: "Texas Medical Center Expansion Building 7",
    date: "04/08/2026", location: "Houston, Texas", zip: "77002",
    docs: "Available", datePosted: "2026-02-25", stage: "Pre-Bid", value: "$120M",
    state: "tx", county: "Harris", trades: ["concrete-construction", "hvac", "plumbing", "electrical-low-voltage"],
    buildingUse: "clinic-hospital-medical", constructionType: "commercial",
    projectType: "new-construction-with-site-work", laborStatus: "non-union",
    keywords: ["hospital", "medical", "MEP"],
  },
  {
    id: "p50", name: "San Antonio River Walk Hotel Renovation",
    date: "03/13/2026", location: "San Antonio, Texas", zip: "78205",
    docs: "Available", datePosted: "2026-02-18", stage: "Bidding", value: "$9.2M",
    state: "tx", county: "Bexar", trades: ["interior-walls-ceilings-insulation", "flooring", "painting-wallcovering"],
    buildingUse: "hotel-motel", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "non-union",
    keywords: ["hotel", "renovation", "hospitality"],
  },
  {
    id: "p51", name: "Fort Worth ISD High School New Construction",
    date: "04/08/2026", location: "Fort Worth, Texas", zip: "76102",
    docs: "Available", datePosted: "2026-03-01", stage: "Pre-Bid", value: "$45M",
    state: "tx", county: "Tarrant", trades: ["concrete-construction", "metal-steel-construction", "roofing-thermal-moisture", "hvac"],
    buildingUse: "educational-school-university", constructionType: "commercial",
    projectType: "new-construction-with-site-work", laborStatus: "non-union",
    keywords: ["high school", "new construction", "K-12"],
  },
  {
    id: "p52", name: "Plano Corporate Headquarters Building",
    date: "04/09/2026", location: "Plano, Texas", zip: "75023",
    docs: "Available", datePosted: "2026-03-10", stage: "Pre-Bid", value: "$72M",
    state: "tx", county: "Collin", trades: ["concrete-construction", "metal-steel-construction", "exterior-siding-masonry"],
    buildingUse: "office", constructionType: "commercial",
    projectType: "new-construction-with-site-work", laborStatus: "non-union",
    keywords: ["corporate headquarters", "office tower"],
  },
  {
    id: "p53", name: "Harris County Sheriff CCTV Infrastructure",
    date: "04/09/2026", location: "Houston, Texas", zip: "77002",
    docs: "Matches Found", datePosted: "2026-03-15", stage: "Bidding", value: "$1.8M",
    state: "tx", county: "Harris", trades: ["electrical-low-voltage", "special-construction"],
    buildingUse: "fire-police-station", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "prevailing-wage",
    keywords: ["CCTV", "surveillance", "security camera"],
  },
  {
    id: "p54", name: "El Paso County Courthouse Security System",
    date: "04/10/2026", location: "El Paso, Texas", zip: "79901",
    docs: "Matches Found", datePosted: "2026-03-07", stage: "Bidding", value: "$540K",
    state: "tx", county: "El Paso", trades: ["electrical-low-voltage", "specialties"],
    buildingUse: "municipal", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "prevailing-wage",
    keywords: ["access control", "security camera", "intrusion detection"],
  },
  {
    id: "p55", name: "Austin-Bergstrom Airport Concourse C Expansion",
    date: "04/10/2026", location: "Austin, Texas", zip: "78701",
    docs: "Available", datePosted: "2026-02-20", stage: "Pre-Bid", value: "$185M",
    state: "tx", county: "Travis", trades: ["concrete-construction", "metal-steel-construction", "hvac", "plumbing"],
    buildingUse: "transportation-terminal", constructionType: "commercial",
    projectType: "addition", laborStatus: "non-union",
    keywords: ["airport", "concourse", "expansion"],
  },
  {
    id: "p56", name: "Houston Luxury Apartment Tower",
    date: "04/11/2026", location: "Houston, Texas", zip: "77002",
    docs: "Available", datePosted: "2026-03-05", stage: "Pre-Bid", value: "$88M",
    state: "tx", county: "Harris", trades: ["concrete-construction", "plumbing", "hvac"],
    buildingUse: "multi-residential", constructionType: "multi-family-residential",
    projectType: "new-construction-with-site-work", laborStatus: "non-union",
    keywords: ["high-rise", "residential", "concrete"],
  },
  {
    id: "p57", name: "Dallas Logistics Hub Warehouse Complex",
    date: "04/11/2026", location: "Dallas, Texas", zip: "75201",
    docs: "Available", datePosted: "2026-03-12", stage: "Pre-Bid", value: "$34M",
    state: "tx", county: "Dallas", trades: ["metal-steel-construction", "concrete-construction", "roofing-thermal-moisture"],
    buildingUse: "warehouse-distribution", constructionType: "industrial",
    projectType: "new-construction-with-site-work", laborStatus: "non-union",
    keywords: ["warehouse", "logistics", "tilt-up"],
  },
  {
    id: "p58", name: "San Antonio USD School Safety Upgrade",
    date: "04/12/2026", location: "San Antonio, Texas", zip: "78205",
    docs: "Matches Found", datePosted: "2026-03-16", stage: "Bidding", value: "$920K",
    state: "tx", county: "Bexar", trades: ["specialties", "electrical-low-voltage"],
    buildingUse: "educational-school-university", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "non-union",
    keywords: ["alarm", "intrusion detection", "security system"],
  },
  {
    id: "p59", name: "Lubbock VA Medical Center Renovation",
    date: "04/12/2026", location: "Lubbock, Texas", zip: "79401",
    docs: "Available", datePosted: "2026-02-15", stage: "Bidding", value: "$6.3M",
    state: "tx", county: "Lubbock", trades: ["hvac", "plumbing", "electrical-low-voltage"],
    buildingUse: "clinic-hospital-medical", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "prevailing-wage",
    keywords: ["VA", "medical", "renovation"],
  },
  {
    id: "p60", name: "Corpus Christi Port Security & Infrastructure",
    date: "04/13/2026", location: "Corpus Christi, Texas", zip: "78401",
    docs: "Available", datePosted: "2026-03-08", stage: "Pre-Bid", value: "$14M",
    state: "tx", county: "Nueces", trades: ["electrical-low-voltage", "demolition-site-construction"],
    buildingUse: "docks-marina", constructionType: "civil",
    projectType: "renovation-remodel-repair", laborStatus: "prevailing-wage",
    keywords: ["port", "infrastructure", "surveillance"],
  },

  // ── FLORIDA PROJECTS ─────────────────────────────────────────────────────────
  {
    id: "p61", name: "Miami-Dade Schools Security Camera Rollout",
    date: "04/13/2026", location: "Miami, Florida", zip: "33101",
    docs: "Matches Found", datePosted: "2026-03-19", stage: "Bidding", value: "$2.4M",
    state: "fl", county: "Miami-Dade", trades: ["electrical-low-voltage", "specialties"],
    buildingUse: "educational-school-university", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "non-union",
    keywords: ["security camera", "CCTV", "access control"],
  },
  {
    id: "p62", name: "Tampa International Airport Terminal F Expansion",
    date: "03/14/2026", location: "Tampa, Florida", zip: "33602",
    docs: "Available", datePosted: "2026-02-28", stage: "Pre-Bid", value: "$210M",
    state: "fl", county: "Hillsborough", trades: ["concrete-construction", "metal-steel-construction", "hvac"],
    buildingUse: "transportation-terminal", constructionType: "commercial",
    projectType: "addition", laborStatus: "non-union",
    keywords: ["airport", "terminal expansion", "airside"],
  },
  {
    id: "p63", name: "Orlando Medical Center Patient Tower",
    date: "03/15/2026", location: "Orlando, Florida", zip: "32801",
    docs: "Available", datePosted: "2026-03-01", stage: "Pre-Bid", value: "$145M",
    state: "fl", county: "Orange", trades: ["concrete-construction", "hvac", "plumbing", "electrical-low-voltage"],
    buildingUse: "clinic-hospital-medical", constructionType: "commercial",
    projectType: "new-construction-with-site-work", laborStatus: "non-union",
    keywords: ["hospital tower", "patient", "MEP"],
  },
  {
    id: "p64", name: "Broward County Courthouse Security Integration",
    date: "04/14/2026", location: "Fort Lauderdale, Florida", zip: "33301",
    docs: "Matches Found", datePosted: "2026-03-14", stage: "Bidding", value: "$1.1M",
    state: "fl", county: "Broward", trades: ["electrical-low-voltage", "special-construction"],
    buildingUse: "municipal", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "prevailing-wage",
    keywords: ["access control", "security camera", "intrusion detection"],
  },
  {
    id: "p65", name: "Jacksonville Naval Air Station Facility Upgrade",
    date: "03/16/2026", location: "Jacksonville, Florida", zip: "32202",
    docs: "Available", datePosted: "2026-02-20", stage: "Bidding", value: "$19M",
    state: "fl", county: "Duval", trades: ["roofing-thermal-moisture", "hvac", "electrical-low-voltage"],
    buildingUse: "military", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "prevailing-wage",
    keywords: ["military", "facility", "renovation"],
  },
  {
    id: "p66", name: "Miami Beach Convention Center Addition",
    date: "04/14/2026", location: "Miami Beach, Florida", zip: "33139",
    docs: "Available", datePosted: "2026-03-10", stage: "Pre-Bid", value: "$78M",
    state: "fl", county: "Miami-Dade", trades: ["concrete-construction", "metal-steel-construction", "hvac"],
    buildingUse: "conference-convention-center", constructionType: "commercial",
    projectType: "addition", laborStatus: "non-union",
    keywords: ["convention center", "ballroom", "expansion"],
  },
  {
    id: "p67", name: "Sarasota County Schools HVAC Replacement",
    date: "04/15/2026", location: "Sarasota, Florida", zip: "34230",
    docs: "Available", datePosted: "2026-03-05", stage: "Bidding", value: "$3.7M",
    state: "fl", county: "Sarasota", trades: ["hvac"],
    buildingUse: "educational-school-university", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "non-union",
    keywords: ["HVAC", "schools", "mechanical"],
  },
  {
    id: "p68", name: "Palm Beach Luxury Resort Renovation",
    date: "04/15/2026", location: "Palm Beach, Florida", zip: "33480",
    docs: "Available", datePosted: "2026-03-08", stage: "Pre-Bid", value: "$24M",
    state: "fl", county: "Palm Beach", trades: ["interior-walls-ceilings-insulation", "flooring", "painting-wallcovering", "plumbing"],
    buildingUse: "hotel-motel", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "non-union",
    keywords: ["resort", "luxury", "renovation"],
  },
  {
    id: "p69", name: "Gainesville UF Science Complex Phase 2",
    date: "04/16/2026", location: "Gainesville, Florida", zip: "32601",
    docs: "Available", datePosted: "2026-02-28", stage: "Pre-Bid", value: "$52M",
    state: "fl", county: "Alachua", trades: ["concrete-construction", "hvac", "plumbing", "electrical-low-voltage"],
    buildingUse: "educational-school-university", constructionType: "commercial",
    projectType: "new-construction-with-site-work", laborStatus: "non-union",
    keywords: ["university", "science", "research"],
  },
  {
    id: "p70", name: "Tallahassee State Capitol Security System",
    date: "04/16/2026", location: "Tallahassee, Florida", zip: "32301",
    docs: "Matches Found", datePosted: "2026-03-16", stage: "Bidding", value: "$830K",
    state: "fl", county: "Leon", trades: ["electrical-low-voltage", "specialties"],
    buildingUse: "municipal", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "prevailing-wage",
    keywords: ["security camera", "access control", "card reader"],
  },

  // ── NEW YORK PROJECTS ────────────────────────────────────────────────────────
  {
    id: "p71", name: "NYC Transit Authority Station Security Cameras",
    date: "04/17/2026", location: "New York, New York", zip: "10001",
    docs: "Matches Found", datePosted: "2026-03-20", stage: "Bidding", value: "$6.8M",
    state: "ny", county: "New York", trades: ["electrical-low-voltage", "special-construction"],
    buildingUse: "transportation-terminal", constructionType: "civil",
    projectType: "renovation-remodel-repair", laborStatus: "union",
    keywords: ["CCTV", "surveillance", "security camera"],
  },
  {
    id: "p72", name: "Bronx Community College Science Building",
    date: "04/17/2026", location: "Bronx, New York", zip: "10451",
    docs: "Available", datePosted: "2026-03-05", stage: "Pre-Bid", value: "$44M",
    state: "ny", county: "Bronx", trades: ["concrete-construction", "hvac", "plumbing"],
    buildingUse: "educational-school-university", constructionType: "commercial",
    projectType: "new-construction-with-site-work", laborStatus: "union",
    keywords: ["community college", "science", "new building"],
  },
  {
    id: "p73", name: "Brooklyn Hospital Center Renovation",
    date: "03/17/2026", location: "Brooklyn, New York", zip: "11201",
    docs: "Available", datePosted: "2026-02-20", stage: "Bidding", value: "$31M",
    state: "ny", county: "Kings", trades: ["hvac", "plumbing", "electrical-low-voltage"],
    buildingUse: "clinic-hospital-medical", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "union",
    keywords: ["hospital", "renovation", "MEP"],
  },
  {
    id: "p74", name: "Queens Library System Renovation Program",
    date: "04/18/2026", location: "Queens, New York", zip: "11354",
    docs: "Available", datePosted: "2026-03-01", stage: "Pre-Bid", value: "$8.5M",
    state: "ny", county: "Queens", trades: ["interior-walls-ceilings-insulation", "flooring", "electrical-low-voltage"],
    buildingUse: "library", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "union",
    keywords: ["library", "renovation", "ADA"],
  },
  {
    id: "p75", name: "Albany State Capitol Security Modernization",
    date: "04/18/2026", location: "Albany, New York", zip: "12207",
    docs: "Matches Found", datePosted: "2026-03-15", stage: "Bidding", value: "$2.2M",
    state: "ny", county: "Albany", trades: ["electrical-low-voltage", "specialties"],
    buildingUse: "municipal", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "prevailing-wage",
    keywords: ["access control", "security camera", "surveillance"],
  },
  {
    id: "p76", name: "Hudson Yards Phase 3 Mixed-Use Tower",
    date: "04/19/2026", location: "New York, New York", zip: "10001",
    docs: "Available", datePosted: "2026-03-10", stage: "Pre-Bid", value: "$340M",
    state: "ny", county: "New York", trades: ["concrete-construction", "metal-steel-construction", "hvac"],
    buildingUse: "mixed-use", constructionType: "multi-family-residential",
    projectType: "new-construction-with-site-work", laborStatus: "union",
    keywords: ["high-rise", "mixed-use", "tower"],
  },
  {
    id: "p77", name: "Buffalo Public School HVAC & Security Upgrade",
    date: "04/19/2026", location: "Buffalo, New York", zip: "14202",
    docs: "Matches Found", datePosted: "2026-03-12", stage: "Bidding", value: "$4.1M",
    state: "ny", county: "Erie", trades: ["hvac", "electrical-low-voltage", "specialties"],
    buildingUse: "educational-school-university", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "union",
    keywords: ["HVAC", "alarm", "security system"],
  },
  {
    id: "p78", name: "JFK Airport Terminal 6 Redevelopment",
    date: "04/20/2026", location: "Jamaica, New York", zip: "11433",
    docs: "Available", datePosted: "2026-02-10", stage: "Pre-Bid", value: "$470M",
    state: "ny", county: "Queens", trades: ["concrete-construction", "metal-steel-construction", "hvac", "electrical-low-voltage"],
    buildingUse: "transportation-terminal", constructionType: "commercial",
    projectType: "new-construction-with-site-work", laborStatus: "union",
    keywords: ["airport", "terminal", "redevelopment"],
  },
  {
    id: "p79", name: "Rochester Medical Center Patient Wing",
    date: "04/20/2026", location: "Rochester, New York", zip: "14604",
    docs: "Available", datePosted: "2026-03-08", stage: "Pre-Bid", value: "$62M",
    state: "ny", county: "Monroe", trades: ["concrete-construction", "hvac", "plumbing"],
    buildingUse: "clinic-hospital-medical", constructionType: "commercial",
    projectType: "addition", laborStatus: "union",
    keywords: ["hospital", "patient tower", "MEP"],
  },
  {
    id: "p80", name: "Staten Island Ferry Terminal Upgrade",
    date: "04/21/2026", location: "St. George, New York", zip: "10301",
    docs: "Available", datePosted: "2026-02-28", stage: "Bidding", value: "$18M",
    state: "ny", county: "Richmond", trades: ["concrete-construction", "electrical-low-voltage"],
    buildingUse: "transportation-terminal", constructionType: "civil",
    projectType: "renovation-remodel-repair", laborStatus: "prevailing-wage",
    keywords: ["ferry terminal", "infrastructure", "civil"],
  },

  // ── COLORADO, OREGON, ARIZONA ────────────────────────────────────────────────
  {
    id: "p81", name: "Denver International Airport Concourse B Security",
    date: "04/21/2026", location: "Denver, Colorado", zip: "80202",
    docs: "Matches Found", datePosted: "2026-03-17", stage: "Bidding", value: "$3.2M",
    state: "co", county: "Denver", trades: ["electrical-low-voltage", "special-construction"],
    buildingUse: "transportation-terminal", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "prevailing-wage",
    keywords: ["security camera", "access control", "surveillance"],
  },
  {
    id: "p82", name: "Colorado Springs VA Medical Center Expansion",
    date: "04/22/2026", location: "Colorado Springs, Colorado", zip: "80903",
    docs: "Available", datePosted: "2026-03-05", stage: "Pre-Bid", value: "$48M",
    state: "co", county: "El Paso", trades: ["concrete-construction", "hvac", "plumbing"],
    buildingUse: "clinic-hospital-medical", constructionType: "commercial",
    projectType: "addition", laborStatus: "prevailing-wage",
    keywords: ["VA hospital", "medical", "expansion"],
  },
  {
    id: "p83", name: "Boulder County Courthouse Renovation",
    date: "03/18/2026", location: "Boulder, Colorado", zip: "80301",
    docs: "Available", datePosted: "2026-02-25", stage: "Bidding", value: "$5.8M",
    state: "co", county: "Boulder", trades: ["interior-walls-ceilings-insulation", "hvac", "electrical-low-voltage"],
    buildingUse: "municipal", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "prevailing-wage",
    keywords: ["courthouse", "renovation", "ADA"],
  },
  {
    id: "p84", name: "Portland Light Rail Extension Infrastructure",
    date: "04/22/2026", location: "Portland, Oregon", zip: "97201",
    docs: "Available", datePosted: "2026-03-08", stage: "Pre-Bid", value: "$92M",
    state: "or", county: "Multnomah", trades: ["demolition-site-construction", "concrete-construction", "electrical-low-voltage"],
    buildingUse: "transportation-terminal", constructionType: "civil",
    projectType: "new-construction-with-site-work", laborStatus: "prevailing-wage",
    keywords: ["light rail", "transit", "infrastructure"],
  },
  {
    id: "p85", name: "Eugene School District Security System",
    date: "04/23/2026", location: "Eugene, Oregon", zip: "97401",
    docs: "Matches Found", datePosted: "2026-03-16", stage: "Bidding", value: "$740K",
    state: "or", county: "Lane", trades: ["electrical-low-voltage", "specialties"],
    buildingUse: "educational-school-university", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "prevailing-wage",
    keywords: ["intrusion detection", "access control", "alarm"],
  },
  {
    id: "p86", name: "Salem State Hospital Renovation Phase 2",
    date: "03/19/2026", location: "Salem, Oregon", zip: "97301",
    docs: "Available", datePosted: "2026-02-20", stage: "Bidding", value: "$22M",
    state: "or", county: "Marion", trades: ["roofing-thermal-moisture", "hvac", "interior-walls-ceilings-insulation"],
    buildingUse: "clinic-hospital-medical", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "prevailing-wage",
    keywords: ["hospital", "renovation", "seismic"],
  },
  {
    id: "p87", name: "Phoenix Sky Harbor Airport Security Upgrade",
    date: "04/23/2026", location: "Phoenix, Arizona", zip: "85001",
    docs: "Matches Found", datePosted: "2026-03-19", stage: "Bidding", value: "$4.5M",
    state: "az", county: "Maricopa", trades: ["electrical-low-voltage", "special-construction"],
    buildingUse: "transportation-terminal", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "non-union",
    keywords: ["CCTV", "security camera", "access control"],
  },
  {
    id: "p88", name: "Tucson USD Middle School Construction",
    date: "04/24/2026", location: "Tucson, Arizona", zip: "85701",
    docs: "Available", datePosted: "2026-03-02", stage: "Pre-Bid", value: "$18M",
    state: "az", county: "Pima", trades: ["concrete-construction", "roofing-thermal-moisture", "hvac"],
    buildingUse: "educational-school-university", constructionType: "commercial",
    projectType: "new-construction-with-site-work", laborStatus: "non-union",
    keywords: ["school", "new construction", "K-12"],
  },
  {
    id: "p89", name: "Scottsdale Mixed-Use Development",
    date: "04/24/2026", location: "Scottsdale, Arizona", zip: "85251",
    docs: "Available", datePosted: "2026-03-14", stage: "Pre-Bid", value: "$63M",
    state: "az", county: "Maricopa", trades: ["concrete-construction", "metal-steel-construction", "exterior-siding-masonry"],
    buildingUse: "mixed-use", constructionType: "multi-family-residential",
    projectType: "new-construction-with-site-work", laborStatus: "non-union",
    keywords: ["mixed-use", "retail", "residential"],
  },
  {
    id: "p90", name: "Mesa Community College HVAC System Replacement",
    date: "04/25/2026", location: "Mesa, Arizona", zip: "85201",
    docs: "Available", datePosted: "2026-02-28", stage: "Bidding", value: "$3.1M",
    state: "az", county: "Maricopa", trades: ["hvac"],
    buildingUse: "educational-school-university", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "non-union",
    keywords: ["HVAC", "community college", "mechanical"],
  },

  // ── NEVADA, ILLINOIS, GEORGIA ─────────────────────────────────────────────────
  {
    id: "p91", name: "Las Vegas Strip Casino Security Integration",
    date: "04/25/2026", location: "Las Vegas, Nevada", zip: "89101",
    docs: "Matches Found", datePosted: "2026-03-18", stage: "Bidding", value: "$8.9M",
    state: "nv", county: "Clark", trades: ["electrical-low-voltage", "special-construction", "specialties"],
    buildingUse: "casino", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "non-union",
    keywords: ["CCTV", "surveillance", "security camera", "access control"],
  },
  {
    id: "p92", name: "Reno Airport Terminal 2 Security Upgrade",
    date: "04/26/2026", location: "Reno, Nevada", zip: "89501",
    docs: "Matches Found", datePosted: "2026-03-10", stage: "Bidding", value: "$2.1M",
    state: "nv", county: "Washoe", trades: ["electrical-low-voltage", "specialties"],
    buildingUse: "transportation-terminal", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "non-union",
    keywords: ["security camera", "access control", "intrusion detection"],
  },
  {
    id: "p93", name: "Chicago Transit Authority Station Renovation",
    date: "04/26/2026", location: "Chicago, Illinois", zip: "60601",
    docs: "Available", datePosted: "2026-03-05", stage: "Pre-Bid", value: "$35M",
    state: "il", county: "Cook", trades: ["concrete-construction", "metal-steel-construction", "electrical-low-voltage"],
    buildingUse: "transportation-terminal", constructionType: "civil",
    projectType: "renovation-remodel-repair", laborStatus: "union",
    keywords: ["transit", "station", "renovation"],
  },
  {
    id: "p94", name: "Cook County Hospital Expansion",
    date: "04/27/2026", location: "Chicago, Illinois", zip: "60601",
    docs: "Available", datePosted: "2026-02-20", stage: "Pre-Bid", value: "$88M",
    state: "il", county: "Cook", trades: ["concrete-construction", "hvac", "plumbing", "electrical-low-voltage"],
    buildingUse: "clinic-hospital-medical", constructionType: "commercial",
    projectType: "addition", laborStatus: "union",
    keywords: ["hospital", "expansion", "MEP"],
  },
  {
    id: "p95", name: "Aurora School District Security Program",
    date: "04/27/2026", location: "Aurora, Illinois", zip: "60505",
    docs: "Matches Found", datePosted: "2026-03-14", stage: "Bidding", value: "$1.3M",
    state: "il", county: "DuPage", trades: ["electrical-low-voltage", "specialties"],
    buildingUse: "educational-school-university", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "union",
    keywords: ["security camera", "access control", "alarm"],
  },
  {
    id: "p96", name: "Atlanta Airport Concourse T CCTV Expansion",
    date: "04/28/2026", location: "Atlanta, Georgia", zip: "30301",
    docs: "Matches Found", datePosted: "2026-03-17", stage: "Bidding", value: "$5.6M",
    state: "ga", county: "Fulton", trades: ["electrical-low-voltage", "special-construction"],
    buildingUse: "transportation-terminal", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "non-union",
    keywords: ["CCTV", "surveillance", "security camera"],
  },
  {
    id: "p97", name: "Savannah Port Authority Infrastructure Upgrade",
    date: "03/20/2026", location: "Savannah, Georgia", zip: "31401",
    docs: "Available", datePosted: "2026-03-02", stage: "Pre-Bid", value: "$47M",
    state: "ga", county: "Chatham", trades: ["concrete-construction", "electrical-low-voltage", "demolition-site-construction"],
    buildingUse: "docks-marina", constructionType: "civil",
    projectType: "renovation-remodel-repair", laborStatus: "non-union",
    keywords: ["port", "infrastructure", "marine"],
  },
  {
    id: "p98", name: "Atlanta VA Medical Center Renovation",
    date: "04/28/2026", location: "Decatur, Georgia", distance: "—", zip: "30030",
    docs: "Available", datePosted: "2026-02-25", stage: "Bidding", value: "$24M",
    state: "ga", county: "DeKalb", trades: ["hvac", "plumbing", "roofing-thermal-moisture"],
    buildingUse: "clinic-hospital-medical", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "prevailing-wage",
    keywords: ["VA", "medical center", "renovation"],
  },
  {
    id: "p99", name: "Gwinnett County School District Safety Upgrade",
    date: "04/29/2026", location: "Lawrenceville, Georgia", distance: "—", zip: "30046",
    docs: "Matches Found", datePosted: "2026-03-11", stage: "Bidding", value: "$1.7M",
    state: "ga", county: "Gwinnett", trades: ["specialties", "electrical-low-voltage"],
    buildingUse: "educational-school-university", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "non-union",
    keywords: ["alarm", "intrusion detection", "security system"],
  },
  {
    id: "p100", name: "Columbus Municipal Complex New Construction",
    date: "03/20/2026", location: "Columbus, Georgia", distance: "—", zip: "31901",
    docs: "Available", datePosted: "2026-03-06", stage: "Pre-Bid", value: "$16M",
    state: "ga", county: "Muscogee", trades: ["concrete-construction", "metal-steel-construction", "hvac"],
    buildingUse: "municipal", constructionType: "commercial",
    projectType: "new-construction-with-site-work", laborStatus: "prevailing-wage",
    keywords: ["municipal", "government", "new construction"],
  },

  // ── NC, NJ, OH, PA, VA, MD, MI ───────────────────────────────────────────────
  {
    id: "p101", name: "Charlotte Douglas Airport Security System",
    date: "04/29/2026", location: "Charlotte, North Carolina", distance: "—", zip: "28202",
    docs: "Matches Found", datePosted: "2026-03-15", stage: "Bidding", value: "$3.8M",
    state: "nc", county: "Mecklenburg", trades: ["electrical-low-voltage", "special-construction"],
    buildingUse: "transportation-terminal", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "non-union",
    keywords: ["security camera", "access control", "CCTV"],
  },
  {
    id: "p102", name: "Raleigh-Durham Hospital Expansion",
    date: "04/30/2026", location: "Durham, North Carolina", distance: "—", zip: "27701",
    docs: "Available", datePosted: "2026-03-01", stage: "Pre-Bid", value: "$75M",
    state: "nc", county: "Durham", trades: ["concrete-construction", "hvac", "plumbing"],
    buildingUse: "clinic-hospital-medical", constructionType: "commercial",
    projectType: "addition", laborStatus: "non-union",
    keywords: ["hospital", "expansion", "patient care"],
  },
  {
    id: "p103", name: "Newark NJ Transit Hub Renovation",
    date: "04/30/2026", location: "Newark, New Jersey", distance: "—", zip: "07102",
    docs: "Available", datePosted: "2026-03-05", stage: "Bidding", value: "$28M",
    state: "nj", county: "Essex", trades: ["concrete-construction", "electrical-low-voltage", "interior-walls-ceilings-insulation"],
    buildingUse: "transportation-terminal", constructionType: "civil",
    projectType: "renovation-remodel-repair", laborStatus: "prevailing-wage",
    keywords: ["transit", "hub", "renovation"],
  },
  {
    id: "p104", name: "Bergen County Schools Security Rollout",
    date: "04/30/2026", location: "Hackensack, New Jersey", distance: "—", zip: "07601",
    docs: "Matches Found", datePosted: "2026-03-16", stage: "Bidding", value: "$2.9M",
    state: "nj", county: "Bergen", trades: ["electrical-low-voltage", "specialties"],
    buildingUse: "educational-school-university", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "prevailing-wage",
    keywords: ["security camera", "access control", "intercom"],
  },
  {
    id: "p105", name: "Columbus Ohio State Medical Center Addition",
    date: "04/30/2026", location: "Columbus, Ohio", distance: "—", zip: "43215",
    docs: "Available", datePosted: "2026-02-15", stage: "Pre-Bid", value: "$110M",
    state: "oh", county: "Franklin", trades: ["concrete-construction", "hvac", "plumbing", "electrical-low-voltage"],
    buildingUse: "clinic-hospital-medical", constructionType: "commercial",
    projectType: "addition", laborStatus: "union",
    keywords: ["hospital", "medical center", "addition"],
  },
  {
    id: "p106", name: "Cleveland Hopkins Airport Terminal Renovation",
    date: "04/30/2026", location: "Cleveland, Ohio", distance: "—", zip: "44113",
    docs: "Available", datePosted: "2026-03-08", stage: "Bidding", value: "$42M",
    state: "oh", county: "Cuyahoga", trades: ["interior-walls-ceilings-insulation", "flooring", "hvac", "electrical-low-voltage"],
    buildingUse: "transportation-terminal", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "union",
    keywords: ["airport", "terminal", "renovation"],
  },
  {
    id: "p107", name: "Philadelphia School District Security System",
    date: "04/30/2026", location: "Philadelphia, Pennsylvania", distance: "—", zip: "19102",
    docs: "Matches Found", datePosted: "2026-03-18", stage: "Bidding", value: "$3.5M",
    state: "pa", county: "Philadelphia", trades: ["electrical-low-voltage", "specialties"],
    buildingUse: "educational-school-university", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "prevailing-wage",
    keywords: ["security camera", "CCTV", "access control"],
  },
  {
    id: "p108", name: "Pittsburgh Children's Hospital Renovation",
    date: "04/30/2026", location: "Pittsburgh, Pennsylvania", distance: "—", zip: "15222",
    docs: "Available", datePosted: "2026-02-20", stage: "Pre-Bid", value: "$56M",
    state: "pa", county: "Allegheny", trades: ["hvac", "plumbing", "interior-walls-ceilings-insulation"],
    buildingUse: "clinic-hospital-medical", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "union",
    keywords: ["children's hospital", "renovation", "MEP"],
  },
  {
    id: "p109", name: "Richmond VA Courthouse Security Integration",
    date: "04/29/2026", location: "Richmond, Virginia", distance: "—", zip: "23220",
    docs: "Matches Found", datePosted: "2026-03-13", stage: "Bidding", value: "$1.4M",
    state: "va", county: "Richmond City", trades: ["electrical-low-voltage", "special-construction"],
    buildingUse: "municipal", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "prevailing-wage",
    keywords: ["access control", "security camera", "intercom"],
  },
  {
    id: "p110", name: "Pentagon Metro Station Security Upgrade",
    date: "04/29/2026", location: "Arlington, Virginia", distance: "—", zip: "22201",
    docs: "Matches Found", datePosted: "2026-03-09", stage: "Bidding", value: "$4.8M",
    state: "va", county: "Arlington", trades: ["electrical-low-voltage", "special-construction"],
    buildingUse: "transportation-terminal", constructionType: "civil",
    projectType: "renovation-remodel-repair", laborStatus: "prevailing-wage",
    keywords: ["CCTV", "surveillance", "security camera", "access control"],
  },
  {
    id: "p111", name: "Baltimore BWI Airport Security System Overhaul",
    date: "04/28/2026", location: "Linthicum, Maryland", distance: "—", zip: "21090",
    docs: "Matches Found", datePosted: "2026-03-14", stage: "Bidding", value: "$6.2M",
    state: "md", county: "Anne Arundel", trades: ["electrical-low-voltage", "special-construction", "specialties"],
    buildingUse: "transportation-terminal", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "prevailing-wage",
    keywords: ["security camera", "access control", "surveillance"],
  },
  {
    id: "p112", name: "Montgomery County School District Safety",
    date: "04/28/2026", location: "Rockville, Maryland", distance: "—", zip: "20850",
    docs: "Matches Found", datePosted: "2026-03-10", stage: "Bidding", value: "$2.1M",
    state: "md", county: "Montgomery", trades: ["electrical-low-voltage", "specialties"],
    buildingUse: "educational-school-university", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "prevailing-wage",
    keywords: ["intrusion detection", "alarm", "security system"],
  },
  {
    id: "p113", name: "Detroit Medical Center New Patient Tower",
    date: "03/21/2026", location: "Detroit, Michigan", distance: "—", zip: "48226",
    docs: "Available", datePosted: "2026-02-25", stage: "Pre-Bid", value: "$142M",
    state: "mi", county: "Wayne", trades: ["concrete-construction", "metal-steel-construction", "hvac", "plumbing"],
    buildingUse: "clinic-hospital-medical", constructionType: "commercial",
    projectType: "new-construction-with-site-work", laborStatus: "union",
    keywords: ["hospital", "patient tower", "new construction"],
  },
  {
    id: "p114", name: "Grand Rapids Airport Terminal Expansion",
    date: "04/27/2026", location: "Grand Rapids, Michigan", distance: "—", zip: "49503",
    docs: "Available", datePosted: "2026-03-05", stage: "Pre-Bid", value: "$38M",
    state: "mi", county: "Kent", trades: ["concrete-construction", "hvac", "electrical-low-voltage"],
    buildingUse: "transportation-terminal", constructionType: "commercial",
    projectType: "addition", laborStatus: "union",
    keywords: ["airport", "expansion", "terminal"],
  },
  {
    id: "p115", name: "Ann Arbor University Hospital Security System",
    date: "04/26/2026", location: "Ann Arbor, Michigan", distance: "—", zip: "48104",
    docs: "Matches Found", datePosted: "2026-03-16", stage: "Bidding", value: "$1.9M",
    state: "mi", county: "Washtenaw", trades: ["electrical-low-voltage", "specialties"],
    buildingUse: "clinic-hospital-medical", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "non-union",
    keywords: ["access control", "card reader", "security camera"],
  },
  {
    id: "p116", name: "Minneapolis Light Rail Southwest Extension",
    date: "04/25/2026", location: "Minneapolis, Minnesota", distance: "—", zip: "55401",
    docs: "Available", datePosted: "2026-02-28", stage: "Pre-Bid", value: "$215M",
    state: "mn", county: "Hennepin", trades: ["demolition-site-construction", "concrete-construction", "electrical-low-voltage"],
    buildingUse: "transportation-terminal", constructionType: "civil",
    projectType: "new-construction-with-site-work", laborStatus: "prevailing-wage",
    keywords: ["light rail", "transit", "civil"],
  },
  {
    id: "p117", name: "St. Paul Ramsey County Courthouse Renovation",
    date: "04/24/2026", location: "Saint Paul, Minnesota", distance: "—", zip: "55101",
    docs: "Available", datePosted: "2026-03-02", stage: "Bidding", value: "$7.4M",
    state: "mn", county: "Ramsey", trades: ["interior-walls-ceilings-insulation", "hvac", "electrical-low-voltage"],
    buildingUse: "municipal", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "prevailing-wage",
    keywords: ["courthouse", "renovation", "government"],
  },
  {
    id: "p118", name: "Seattle Amazon HQ2 Security Infrastructure",
    date: "04/23/2026", location: "Seattle, Washington", distance: "5 miles", zip: "98101",
    docs: "Matches Found", datePosted: "2026-03-19", stage: "Pre-Bid", value: "$2.6M",
    state: "wa", county: "King", trades: ["electrical-low-voltage", "special-construction"],
    buildingUse: "office", constructionType: "commercial",
    projectType: "new-construction-no-site-work", laborStatus: "non-union",
    keywords: ["access control", "security camera", "surveillance"],
  },
  {
    id: "p119", name: "Fresno Unified School Security Camera Upgrade",
    date: "04/22/2026", location: "Fresno, California", distance: "46 miles", zip: "93721",
    docs: "Matches Found", datePosted: "2026-03-20", stage: "Bidding", value: "$890K",
    state: "ca", county: "Fresno", trades: ["electrical-low-voltage", "specialties"],
    buildingUse: "educational-school-university", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "prevailing-wage",
    keywords: ["security camera", "CCTV", "surveillance"],
  },
  {
    id: "p120", name: "San Bernardino County Government Center Security",
    date: "04/21/2026", location: "San Bernardino, California", distance: "55 miles", zip: "92401",
    docs: "Matches Found", datePosted: "2026-03-11", stage: "Bidding", value: "$1.5M",
    state: "ca", county: "San Bernardino", trades: ["electrical-low-voltage", "special-construction"],
    buildingUse: "municipal", constructionType: "commercial",
    projectType: "renovation-remodel-repair", laborStatus: "prevailing-wage",
    keywords: ["access control", "security camera", "intrusion detection"],
  },
]
